apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  labels:
    run: nginx-test
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 8443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    run: nginx-test