---
- name: added in 2.4, previouslly you used 'include'
  import_tasks: RedHat.yml
  when: ansible_os_family|lower == 'redhat'
- import_tasks: Debian.yml
  when: ansible_os_family|lower == 'debian'

