---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: vagrant
  become: yes
  become_method: su
  become_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
#  - name: write the apache config file
#    template:
#      src: /srv/httpd.j2
#      dest: /etc/httpd.conf
#    notify:
#    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted

- hosts: dbservers
  remote_user: vagrant
  become: yes
  become_method: su
  become_user: root
  tasks:
  - name: ensure mariadb is at the latest version
    yum:
      name: mariadb-server
      state: latest
  - name: ensure mariadb is running
    service:
      name: mariadb
      state: started
  handlers:
    - name: restart mariadb
      service:
        name: mariadb
        state: restarted
